/**
 * Build-time sitemap generator.
 *
 * The sitemap is generated from src/data/blogPosts.ts so it can never drift
 * out of sync with published content (the previous static public/sitemap.xml
 * had to be hand-edited and went stale). Runs on `vite build` and `vite dev`
 * startup; output goes to dist/public-equivalent via public/ (served statically).
 */
import { writeFileSync, existsSync, unlinkSync } from "node:fs";
import { resolve } from "node:path";
import type { Plugin } from "vite";
import { blogPosts } from "../src/data/blogPosts";
import { SITE_URL, postLastmod } from "../src/lib/seo";

const STATIC_ROUTES: { path: string; changefreq: string; priority: string }[] = [
  { path: "/", changefreq: "weekly", priority: "1.0" },
  { path: "/ventures", changefreq: "monthly", priority: "0.8" },
  { path: "/projects", changefreq: "monthly", priority: "0.8" },
  { path: "/skills", changefreq: "monthly", priority: "0.7" },
  { path: "/blogs", changefreq: "weekly", priority: "0.9" },
  { path: "/contact", changefreq: "yearly", priority: "0.6" },
];

function buildSitemap(): string {
  const today = new Date().toISOString().slice(0, 10);

  const staticUrls = STATIC_ROUTES.map(
    (r) => `  <url>
    <loc>${SITE_URL}${r.path === "/" ? "/" : r.path}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${r.changefreq}</changefreq>
    <priority>${r.priority}</priority>
  </url>`,
  ).join("\n");

  const postUrls = blogPosts
    .map(
      (p) => `  <url>
    <loc>${SITE_URL}/blogs/${p.slug}</loc>
    <lastmod>${postLastmod(p.isoDate, p.dateModified)}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>`,
    )
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Auto-generated by plugins/sitemap-generator.ts — DO NOT EDIT BY HAND.
     Add new posts to src/data/blogPosts.ts and rebuild. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${staticUrls}
${postUrls}
</urlset>
`;
}

export function sitemapGenerator(): Plugin {
  const outPath = resolve(process.cwd(), "public/sitemap.xml");
  let logger: { info: (msg: string) => void } = console;

  return {
    name: "iamabdullah-sitemap-generator",
    apply: "build",
    configResolved(resolvedConfig) {
      logger = resolvedConfig.logger;
    },
    buildStart() {
      writeFileSync(outPath, buildSitemap(), "utf8");
      logger.info(`[sitemap] generated ${blogPosts.length + STATIC_ROUTES.length} URLs`);
    },
  };
}

export function sitemapGeneratorDev(): Plugin {
  const outPath = resolve(process.cwd(), "public/sitemap.xml");

  return {
    name: "iamabdullah-sitemap-generator-dev",
    apply: "serve",
    configureServer(server) {
      // Generate once on dev startup (not watched — avoids dev-time loops)
      writeFileSync(outPath, buildSitemap(), "utf8");
      server.config.logger.info(`[sitemap] dev: ${blogPosts.length + STATIC_ROUTES.length} URLs`);
    },
  };
}

/** Ensure a stale committed sitemap doesn't shadow the generated one. */
export function removeStaleSitemap(): void {
  // Kept for future use; generation overwrites the file deterministically.
  if (existsSync(resolve(process.cwd(), "sitemap.xml.bak"))) {
    unlinkSync(resolve(process.cwd(), "sitemap.xml.bak"));
  }
}
